<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<!--
Design by Free CSS Templates
http://www.freecsstemplates.org
Released for free under a Creative Commons Attribution 3.0 License

Name       : Anodized
Description: A two-column, fixed-width design with a dark color scheme.
Version    : 1.0
Released   : 20120705
-->
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta name="keywords" content="" />
<meta name="description" content="" />
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<title>
	NidhiDemo
</title>
<link href="http://fonts.googleapis.com/css?family=Arvo" rel="stylesheet" type="text/css" />
<link href="http://fonts.googleapis.com/css?family=Bevan" rel="stylesheet" type="text/css" />
<link rel="stylesheet" type="text/css" href="/style/style.css" />
</head>
<body>
<div id="wrapper">
	<div id="header">
		<div id="logo">
			<h3>
		NidhiDemo
			</h3>
		</div>
		<div id="search">
			<form action="" method="post">
				<div>
					<input class="text" name="search" size="32" maxlength="64" />
				</div>
			</form>
		</div>
		<div id="menu">
			<ul>
				<li class="first active">
					<a href="/index">Home</a>
				</li>
				<li>
					<a href="#">Blog</a>
				</li>
				<li>
					<a href="#">Portfolio</a>
				</li>
				<li>
					<a href="#">Downloads</a>
				</li>
				<li>
					<a href="#">About</a>
				</li>
				<li>
					<a href="#">Links</a>
				</li>
				<li class="last">
					<a href="#">Contact</a>
				</li>
			</ul><br class="clearfix" />
		</div>
	</div>
	<div id="page">
		<div id="content">
			<div class="box">
				<h2>

				</h2>
				
			</div>
			<div class="box" id="box-left">
				
				
				
			</div>
			<div class="box" id="box-right">
				<?=$this->layout()->content; ?>
			</div><br class="clearfix" />
		</div>
		<div id="sidebar">
			<div class="box">
				
				
			</div>
			<div class="box">
				
			</div>
		</div><br class="clearfix" />
	</div>
	<div id="page-bottom">
		<div id="page-bottom-content">
			
		</div>
		
	</div>
</div>
<div id="footer">
	&copy; SiteName | 
</div>
</body>
</html>